# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

# ブランチやタグを指定したいとき
[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

# 特定の条件で読み込みたいとき
[[plugins]]
repo = 'elzr-vim-json'
if   = '''! has('kaoriya')'''

# 依存関係を指定したいとき
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo    = 'vim-airline/vim-airline'

# 依存関係を指定したからと言って、自動でインストールはされない（ここは NeoBundle と違う）
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'scrooloose/nerdtree'

#[[plugins]]
#repos = 'scrooloose/syntastic'

## シンタックスのハイライト
#[[plugins]]
#'jelera/vim-javascript-syntax'

# nodejsプラグイン
#[[plugins]]
#node.js
#javascript syntax highlight[[pos = 'pangloss/vim-javascript'


#splitjoin.vim
#'Townk/vim-autoclose'
#'scrooloose/syntastic'
#'tpope/vim-fugitive'
#'jelera/vim-javascript-syntax'
